# The DB master password is never supplied by a human or stored in a .tfvars
# file: it is generated by Terraform, stored only in state (which is encrypted
# in the S3 backend) and Secrets Manager, and referenced by ECS via secret ARN.
# Rotate by tainting this resource (`terraform taint random_password.db`) and
# applying -- Terraform will update both RDS and the Secrets Manager version.
resource "random_password" "db" {
  length  = 32
  special = true
  # RDS master passwords may not contain '/', '@', '"', or spaces.
  override_special = "!#$%&*()-_=+[]{}<>:?"
}

module "networking" {
  source = "../../modules/networking"

  project_name             = var.project_name
  environment              = var.environment
  vpc_cidr                 = var.vpc_cidr
  availability_zones       = var.availability_zones
  public_subnet_cidrs      = var.public_subnet_cidrs
  private_app_subnet_cidrs = var.private_app_subnet_cidrs
  private_db_subnet_cidrs  = var.private_db_subnet_cidrs
  kms_key_arn              = module.kms.data_key_arn
  tags                     = var.tags
}

module "security" {
  source = "../../modules/security"

  project_name           = var.project_name
  environment            = var.environment
  vpc_id                 = module.networking.vpc_id
  alb_ingress_cidrs      = var.alb_ingress_cidrs
  alb_ingress_ipv6_cidrs = var.alb_ingress_ipv6_cidrs
  tags                   = var.tags
}

module "ecr" {
  source = "../../modules/ecr"

  project_name = var.project_name
  environment  = var.environment
  tags         = var.tags
  force_delete = var.ecr_force_delete
}

module "secrets_manager" {
  source = "../../modules/secrets-manager"

  project_name         = var.project_name
  environment          = var.environment
  db_username          = var.db_username
  db_password          = random_password.db.result
  db_name              = var.db_name
  existing_secret_name = var.existing_db_secret_name
  tags                 = var.tags
}

module "iam" {
  source = "../../modules/iam"

  project_name        = var.project_name
  environment         = var.environment
  ecr_repository_arns = [module.ecr.web_repository_arn, module.ecr.api_repository_arn]
  secret_arns         = [module.secrets_manager.db_secret_arn]
  enable_github_oidc  = var.enable_github_oidc
  github_repository   = var.github_repository
  github_allowed_refs = var.github_allowed_refs
  tags                = var.tags
}

module "rds" {
  source = "../../modules/rds"

  project_name            = var.project_name
  environment             = var.environment
  db_username             = var.db_username
  db_password             = random_password.db.result
  db_name                 = var.db_name
  db_instance_class       = var.db_instance_class
  allocated_storage       = var.allocated_storage
  engine_version          = var.engine_version
  backup_retention_period = var.backup_retention_period
  deletion_protection     = var.deletion_protection
  skip_final_snapshot     = var.skip_final_snapshot
  db_subnet_ids           = module.networking.private_db_subnet_ids
  vpc_security_group_ids  = [module.security.postgres_security_group_id]
  tags                    = var.tags
}

module "alb" {
  source = "../../modules/alb"

  project_name      = var.project_name
  environment       = var.environment
  vpc_id            = module.networking.vpc_id
  subnet_ids        = module.networking.public_subnet_ids
  security_group_id = module.security.alb_security_group_id
  certificate_arn   = var.certificate_arn
  health_check_path = var.alb_health_check_path
  tags              = var.tags
}

module "ecs" {
  source = "../../modules/ecs"

  project_name                    = var.project_name
  environment                     = var.environment
  vpc_id                          = module.networking.vpc_id
  subnet_ids                      = module.networking.private_app_subnet_ids
  web_security_group_id           = module.security.web_security_group_id
  api_security_group_id           = module.security.api_security_group_id
  task_execution_role_arn         = module.iam.task_execution_role_arn
  task_role_arn                   = module.iam.task_role_arn
  web_image                       = var.web_image != "" ? var.web_image : format("%s:latest", module.ecr.web_repository_uri)
  api_image                       = var.api_image != "" ? var.api_image : format("%s:latest", module.ecr.api_repository_uri)
  db_host                         = module.rds.db_endpoint
  db_name                         = var.db_name
  db_username                     = var.db_username
  db_secret_arn                   = module.secrets_manager.db_secret_arn
  target_group_arn                = module.alb.target_group_arn
  api_service_discovery_namespace = format("%s-%s.local", var.project_name, var.environment)
  web_desired_count               = var.web_desired_count
  api_desired_count               = var.api_desired_count
  kms_key_arn                     = module.kms.data_key_arn
  tags                            = var.tags
}

module "kms" {
  source = "../../modules/kms"

  project_name = var.project_name
  environment  = var.environment
  tags         = var.tags
}

module "waf" {
  source = "../../modules/waf"

  project_name = var.project_name
  environment  = var.environment
  rate_limit   = var.waf_rate_limit
  tags         = var.tags
}

module "cloudfront" {
  source = "../../modules/cloudfront"

  project_name       = var.project_name
  environment        = var.environment
  origin_domain_name = module.alb.alb_dns_name
  certificate_arn    = var.certificate_arn
  aliases            = var.cloudfront_aliases
  web_acl_arn        = module.waf.web_acl_arn
  tags               = var.tags
}

module "cloudwatch" {
  source = "../../modules/cloudwatch"

  project_name           = var.project_name
  environment            = var.environment
  cluster_name           = module.ecs.cluster_name
  web_service_name       = module.ecs.web_service_name
  api_service_name       = module.ecs.api_service_name
  load_balancer_arn      = module.alb.alb_arn
  target_group_arn       = module.alb.target_group_arn
  db_instance_identifier = module.rds.db_instance_identifier
  alert_email            = var.alert_email
  web_desired_count      = var.web_desired_count
  api_desired_count      = var.api_desired_count
  kms_key_arn            = module.kms.data_key_arn
  tags                   = var.tags
}

module "codedeploy" {
  source = "../../modules/codedeploy"

  project_name            = var.project_name
  environment             = var.environment
  cluster_name            = module.ecs.cluster_name
  web_service_name        = module.ecs.web_service_name
  production_listener_arn = module.alb.production_listener_arn
  blue_target_group_name  = module.alb.target_group_name
  green_target_group_name = module.alb.green_target_group_name
  alarm_names             = module.cloudwatch.deployment_rollback_alarm_names
  tags                    = var.tags
}

module "cloudtrail" {
  source = "../../modules/cloudtrail"

  project_name          = var.project_name
  environment           = var.environment
  kms_key_arn           = module.kms.cloudtrail_key_arn
  log_group_kms_key_arn = module.kms.data_key_arn
  tags                  = var.tags
}

module "backup" {
  source = "../../modules/backup"

  project_name     = var.project_name
  environment      = var.environment
  kms_key_arn      = module.kms.data_key_arn
  rds_instance_arn = module.rds.db_instance_arn
  retention_days   = var.backup_retention_days
  schedule         = var.backup_schedule
  tags             = var.tags
}

output "cloudfront_domain" {
  description = "CloudFront distribution domain name."
  value       = module.cloudfront.domain_name
}

output "alb_dns_name" {
  description = "ALB DNS name."
  value       = module.alb.alb_dns_name
}

output "web_service_name" {
  description = "Web ECS service name."
  value       = module.ecs.web_service_name
}

output "api_service_name" {
  description = "API ECS service name."
  value       = module.ecs.api_service_name
}

output "web_repository_uri" {
  description = "ECR repository URI for the Web service."
  value       = module.ecr.web_repository_uri
}

output "api_repository_uri" {
  description = "ECR repository URI for the API service."
  value       = module.ecr.api_repository_uri
}

output "sns_alerts_topic_arn" {
  description = "SNS topic ARN that CloudWatch alarms publish to."
  value       = module.cloudwatch.sns_topic_arn
}

output "cloudtrail_bucket" {
  description = "S3 bucket storing CloudTrail audit logs."
  value       = module.cloudtrail.bucket_name
}

output "waf_web_acl_arn" {
  description = "ARN of the WAFv2 web ACL protecting CloudFront."
  value       = module.waf.web_acl_arn
}

output "backup_vault_name" {
  description = "Name of the AWS Backup vault holding RDS recovery points."
  value       = module.backup.vault_name
}

output "github_app_deploy_role_arn" {
  description = "IAM role ARN for GitHub Actions app.yml to assume via OIDC (set as AWS_APP_DEPLOY_ROLE_ARN repo variable)."
  value       = module.iam.github_app_deploy_role_arn
}

output "github_terraform_role_arn" {
  description = "IAM role ARN for GitHub Actions infra.yml to assume via OIDC (set as AWS_TERRAFORM_ROLE_ARN repo variable)."
  value       = module.iam.github_terraform_role_arn
}

output "codedeploy_app_name" {
  description = "CodeDeploy application name for the Web service, used by app.yml to trigger blue/green deployments."
  value       = module.codedeploy.app_name
}

output "codedeploy_deployment_group_name" {
  description = "CodeDeploy deployment group name for the Web service."
  value       = module.codedeploy.deployment_group_name
}

output "web_green_target_group_arn" {
  description = "ARN of the green target group for the Web service."
  value       = module.alb.green_target_group_arn
}
